### ISSUE TITLE
Add topics to github plugin

### ISSUE THREAD

**Issue by deku-m** [tbotnz/netbox_floorplan#13]
**Suggestion:**
To try and get more people to your plugin and maybe more contribution.
It might help to add the topics to your plugin under description with the wheel icon.

![251296718-82199d6e-2362-4c98-a55d-15cc5ce9032f](https://github.com/tbotnz/netbox_floorplan/assets/37069737/05761c27-9bae-487a-ad13-85d3bfbe482b)

As i mostly use it to search for plugins using the topic netbox-plugins and see if it is recently updated.

**Comment by tbotnz** [comment]
Done
