### ISSUE TITLE
Background images not working

### ISSUE THREAD

**Issue by Azmodeszer** [tbotnz/netbox_floorplan#26]
There's three inquiries/issues here...

1) Uploading a background image for **locations** is giving me a Python error:

`'NoneType' object has no attribute 'id'`

2) Uploading a background image for **sites** is going through, but there is nothing displayed in the floorplan tab. It's the usual blank canvas. I checked the actual file system, the image is there and has the needed Linux permissions. Do images have to meet certain file type and/or size requirements? The documentation didn't say (or I missed it).

3) When adding (or updating) a floor plan through the Admin page, why is the Tags field required?

Thanks.

Python version: 3.11.2
NetBox version: 3.7.2
netbox_floorplan: 0.4

**Comment by bastianleicht** [comment]
This Issue still comes up. Did anyone fix this?

**Comment by bastianleicht** [comment]
This is the Error Traceback i am getting: 
![grafik](https://github.com/tbotnz/netbox_floorplan/assets/50463419/6139267e-0e0d-42f4-be01-791487776a9b)
