### ISSUE TITLE
Modifications to Supplementary Object (Area)

### ISSUE THREAD

**Issue by justin-davisibm** [tbotnz/netbox_floorplan#6]
First- Thanks for the work you've done on this- I can see it being extremely useful for our team.

We use the equivalent of Supplementary Object (Area) quite heavily in our current DCIM- things like our storage rooms, low load/heavy load tiles, etc. as well as static structures like CRACs and hydraulic lifts.

It would be a huge benefit to be able to:
- lock these areas to their location, so clicking and dragging does not accidentally move them (major usability issue when dealing with a large floorspace)
- permanently setting their depth: Currently if one is positioned over where netbox-floorplan places a newly added rack object, I need to click outside the area for the racks to jump back to foreground
- Set area size in feet/meters, like the overall floorplan
- Snap area to other objects- at least walls/edge of floorplan

**Comment by justin-davisibm** [comment]
Correction: I have to **move** the area out of the way to retrieve the rack that was auto-placed underneath it.

**Comment by tbotnz** [comment]
Thanks @justin-davisibm 

For snapping, there is logic in there already to snap to a common grid but the grid is quite small, possibly some control of the grid may be helpful

Agree all of these features would be nice, feel free to open PR

**Comment by justin-davisibm** [comment]
@tbotnz - I will start taking a crack at a few of these.
